version: '3.8'

services:
  backend:
    build: "./backend"
    container_name: backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
    volumes:
      - ./backend/src:/app/src
    depends_on:
      - database

  frontend:
    build: "./frontend"
    container_name: frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    tty: true

  database:
    image: postgres:11.11-alpine
    restart: always
    container_name: database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "${DB_DATABASE}"
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
